import sqlite3
from datetime import datetime, timedelta
from math import gcd

INDUSTRIES = [
    "Technology",
    "Healthcare",
    "Finance",
    "Manufacturing",
    "Retail",
    "Education",
    "Real Estate",
    "Consulting",
    "Media",
    "Automotive",
    "Energy",
    "Telecommunications",
    "Transportation",
    "Food & Beverage",
    "Pharmaceuticals",
    "Insurance",
    "Legal",
    "Construction",
    "Agriculture",
    "Aerospace",
    "Banking",
    "Biotechnology",
    "Chemicals",
    "Defense",
    "Entertainment",
    "Fashion",
    "Gaming",
    "Hospitality",
    "Logistics",
]

REGIONS = ["North America", "Europe", "Asia Pacific", "Latin America", "Middle East & Africa"]

LEAD_SOURCES = [
    "Website",
    "Referral",
    "Cold Call",
    "Email Campaign",
    "Social Media",
    "Trade Show",
    "Partner",
    "LinkedIn",
    "Google Ads",
    "Content Marketing",
]

LEAD_STATUSES = ["new", "contacted", "qualified", "proposal", "negotiation", "closed-won", "closed-lost"]

OPPORTUNITY_STAGES = ["prospecting", "qualification", "proposal", "negotiation", "closed-won", "closed-lost"]

JOB_TITLES = [
    "CEO",
    "CTO",
    "VP Sales",
    "VP Marketing",
    "Director of Operations",
    "Sales Manager",
    "Marketing Manager",
    "Product Manager",
    "Account Manager",
    "Business Analyst",
    "Project Manager",
    "HR Director",
    "Finance Director",
    "Chief Technology Officer",
    "Chief Marketing Officer",
    "Chief Financial Officer",
    "VP Engineering",
    "VP Product",
    "VP Customer Success",
    "Regional Manager",
    "Territory Manager",
    "Account Executive",
    "Sales Director",
    "Marketing Director",
    "Operations Director",
    "IT Director",
    "Procurement Manager",
    "Supply Chain Manager",
]

DEPARTMENTS = [
    "Sales",
    "Marketing",
    "Engineering",
    "Operations",
    "Finance",
    "HR",
    "Customer Success",
    "IT",
    "Legal",
    "Procurement",
]

COMPANY_NAMES = [
    "Acme Corporation",
    "Tech Solutions Inc",
    "Global Dynamics",
    "Innovation Labs",
    "Future Systems",
    "Digital Partners",
    "Cloud Technologies",
    "Data Analytics Co",
    "Smart Solutions",
    "NextGen Corp",
    "Alpha Industries",
    "Beta Systems",
    "Gamma Technologies",
    "Delta Solutions",
    "Epsilon Corp",
    "Zeta Enterprises",
    "Eta Industries",
    "Theta Systems",
    "Iota Technologies",
    "Kappa Solutions",
    "Lambda Corp",
    "Mu Industries",
    "Nu Systems",
    "Xi Technologies",
    "Omicron Solutions",
    "Pi Enterprises",
    "Rho Industries",
    "Sigma Systems",
    "Tau Technologies",
    "Upsilon Corp",
    "Phi Industries",
    "Chi Systems",
    "Psi Technologies",
    "Omega Solutions",
    "Alpha Beta Corp",
    "Gamma Delta Inc",
    "Epsilon Zeta LLC",
    "Eta Theta Corp",
    "Iota Kappa Inc",
    "Lambda Mu LLC",
    "Nu Xi Corp",
    "Omicron Pi Inc",
    "Rho Sigma LLC",
    "Tau Upsilon Corp",
    "Phi Chi Inc",
    "Psi Omega LLC",
    "Advanced Systems",
    "Premier Technologies",
    "Elite Solutions",
    "Superior Corp",
    "Excellence Inc",
    "Quality Systems",
    "Reliable Technologies",
    "Trusted Solutions",
    "Proven Corp",
    "Established Inc",
    "Renowned Systems",
    "Famous Technologies",
    "Popular Solutions",
    "Leading Corp",
    "Top Industries",
    "Best Systems",
    "Prime Technologies",
    "First Solutions",
    "Number One Corp",
    "Apex Industries",
    "Summit Systems",
    "Peak Technologies",
    "Crest Solutions",
    "Crown Corp",
    "Royal Industries",
    "Noble Systems",
    "Prestigious Technologies",
    "Distinguished Solutions",
    "Honored Corp",
    "Respected Inc",
    "Admired Systems",
    "Valued Technologies",
    "Cherished Solutions",
    "Beloved Corp",
    "Preferred Inc",
    "Chosen Systems",
    "Selected Technologies",
    "Picked Solutions",
    "Chosen Corp",
    "Elected Inc",
    "Voted Systems",
    "Approved Technologies",
    "Accepted Solutions",
    "Agreed Corp",
    "Consented Inc",
    "Approved Systems",
    "Endorsed Technologies",
    "Supported Solutions",
    "Backed Corp",
    "Funded Inc",
    "Invested Systems",
    "Capitalized Technologies",
    "Financed Solutions",
    "Monetized Corp",
    "Profitable Inc",
    "Lucrative Systems",
    "Rewarding Technologies",
    "Beneficial Solutions",
    "Advantageous Corp",
    "Favorable Inc",
    "Positive Systems",
    "Constructive Technologies",
    "Productive Solutions",
    "Effective Corp",
    "Efficient Inc",
    "Streamlined Systems",
    "Optimized Technologies",
    "Enhanced Solutions",
    "Improved Corp",
    "Upgraded Inc",
    "Modernized Systems",
    "Updated Technologies",
    "Refreshed Solutions",
    "Renewed Corp",
    "Revitalized Inc",
    "Rejuvenated Systems",
    "Reinvigorated Technologies",
    "Reenergized Solutions",
    "Recharged Corp",
]

FIRST_NAMES = [
    "John",
    "Jane",
    "Michael",
    "Sarah",
    "David",
    "Lisa",
    "Robert",
    "Jennifer",
    "William",
    "Jessica",
    "James",
    "Ashley",
    "Christopher",
    "Amanda",
    "Daniel",
    "Stephanie",
    "Matthew",
    "Melissa",
    "Anthony",
    "Nicole",
    "Mark",
    "Elizabeth",
    "Donald",
    "Helen",
    "Steven",
    "Deborah",
    "Paul",
    "Dorothy",
    "Andrew",
    "Lisa",
    "Joshua",
    "Nancy",
    "Kenneth",
    "Karen",
    "Kevin",
    "Betty",
    "Brian",
    "Sandra",
    "George",
    "Donna",
    "Timothy",
    "Carol",
    "Ronald",
    "Ruth",
    "Jason",
    "Sharon",
    "Edward",
    "Michelle",
    "Jeffrey",
    "Laura",
    "Ryan",
    "Sarah",
    "Jacob",
    "Kimberly",
    "Gary",
    "Deborah",
    "Nicholas",
    "Dorothy",
    "Eric",
    "Lisa",
    "Jonathan",
    "Nancy",
    "Stephen",
    "Karen",
    "Larry",
    "Betty",
    "Justin",
    "Helen",
    "Scott",
    "Sandra",
    "Brandon",
    "Donna",
    "Benjamin",
    "Carol",
    "Samuel",
    "Ruth",
    "Gregory",
    "Sharon",
    "Alexander",
    "Michelle",
    "Patrick",
    "Laura",
    "Jack",
    "Sarah",
    "Dennis",
    "Kimberly",
    "Jerry",
    "Deborah",
    "Tyler",
    "Dorothy",
    "Aaron",
    "Lisa",
    "Jose",
    "Nancy",
    "Henry",
    "Karen",
    "Adam",
    "Betty",
    "Douglas",
    "Helen",
    "Nathan",
    "Sandra",
    "Peter",
    "Donna",
    "Zachary",
    "Carol",
    "Kyle",
    "Ruth",
    "Noah",
    "Sharon",
    "Alan",
    "Michelle",
    "Ethan",
    "Laura",
    "Jeremy",
    "Sarah",
    "Keith",
    "Kimberly",
    "Christian",
    "Deborah",
    "Austin",
    "Dorothy",
    "Sean",
    "Lisa",
    "Gerald",
    "Nancy",
    "Carl",
    "Karen",
    "Harold",
    "Betty",
    "Wayne",
    "Helen",
    "Arthur",
    "Sandra",
    "Terry",
    "Donna",
    "Lawrence",
    "Carol",
    "Joe",
    "Ruth",
    "Eugene",
    "Sharon",
    "Ralph",
    "Michelle",
    "Bobby",
    "Laura",
    "Louis",
    "Sarah",
    "Philip",
    "Kimberly",
    "Johnny",
    "Deborah",
    "Roy",
    "Dorothy",
    "Roger",
    "Lisa",
    "Howard",
    "Nancy",
    "Juan",
    "Karen",
    "Albert",
    "Betty",
    "Willie",
    "Helen",
    "Elmer",
    "Sandra",
    "Wayne",
    "Donna",
    "Eugene",
    "Carol",
]

LAST_NAMES = [
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Rodriguez",
    "Martinez",
    "Hernandez",
    "Lopez",
    "Gonzalez",
    "Wilson",
    "Anderson",
    "Thomas",
    "Taylor",
    "Moore",
    "Jackson",
    "Martin",
    "Lee",
    "Perez",
    "Thompson",
    "White",
    "Harris",
    "Sanchez",
    "Clark",
    "Ramirez",
    "Lewis",
    "Robinson",
    "Walker",
    "Young",
    "Allen",
    "King",
    "Wright",
    "Scott",
    "Torres",
    "Nguyen",
    "Hill",
    "Flores",
    "Green",
    "Adams",
    "Nelson",
    "Baker",
    "Hall",
    "Rivera",
    "Campbell",
    "Mitchell",
    "Carter",
    "Roberts",
    "Gomez",
    "Phillips",
    "Evans",
    "Turner",
    "Diaz",
    "Parker",
    "Cruz",
    "Edwards",
    "Collins",
    "Reyes",
    "Stewart",
    "Morris",
    "Morales",
    "Murphy",
    "Cook",
    "Rogers",
    "Gutierrez",
    "Ortiz",
    "Morgan",
    "Cooper",
    "Peterson",
    "Bailey",
    "Reed",
    "Kelly",
    "Howard",
    "Ramos",
    "Kim",
    "Cox",
    "Ward",
    "Richardson",
    "Watson",
    "Brooks",
    "Chavez",
    "Wood",
    "James",
    "Bennett",
    "Gray",
    "Mendoza",
    "Ruiz",
    "Hughes",
    "Price",
    "Alvarez",
    "Castillo",
    "Sanders",
    "Patel",
    "Myers",
    "Long",
    "Ross",
    "Foster",
    "Jimenez",
    "Powell",
    "Jenkins",
    "Perry",
    "Russell",
    "Sullivan",
    "Bell",
    "Coleman",
    "Butler",
    "Henderson",
    "Barnes",
    "Gonzales",
    "Fisher",
    "Vasquez",
    "Simmons",
    "Romero",
    "Jordan",
    "Patterson",
    "Alexander",
    "Hamilton",
    "Graham",
    "Reynolds",
    "Griffin",
    "Wallace",
    "Moreno",
    "West",
    "Cole",
    "Hayes",
    "Bryant",
    "Herrera",
    "Gibson",
    "Ellis",
    "Tran",
    "Medina",
    "Aguilar",
    "Stevens",
    "Murray",
    "Ford",
    "Castro",
    "Marshall",
    "Owens",
    "Harrison",
    "Fernandez",
    "McDonald",
    "Woods",
    "Washington",
    "Kennedy",
    "Wells",
    "Vargas",
    "Henry",
    "Chen",
    "Freeman",
    "Webb",
    "Tucker",
    "Guzman",
    "Burns",
    "Crawford",
    "Olson",
    "Simpson",
    "Porter",
    "Hunter",
    "Gordon",
    "Mendez",
    "Silva",
    "Shaw",
    "Snyder",
    "Mason",
    "Dixon",
    "Munoz",
    "Hunt",
    "Hicks",
    "Holmes",
    "Palmer",
    "Wagner",
    "Black",
    "Robertson",
    "Boyd",
    "Rose",
    "Stone",
    "Salazar",
    "Fox",
]

EMAIL_DOMAINS = [
    "gmail.com",
    "yahoo.com",
    "hotmail.com",
    "outlook.com",
    "company.com",
    "business.org",
    "enterprise.net",
    "corporate.com",
    "firm.org",
    "group.com",
    "team.net",
    "office.org",
    "workplace.com",
    "professional.net",
    "executive.org",
    "management.com",
    "leadership.net",
    "strategy.org",
    "operations.com",
    "development.net",
    "innovation.org",
    "technology.com",
    "solutions.net",
    "services.org",
    "consulting.com",
    "advisory.net",
    "partners.org",
    "associates.com",
    "ventures.net",
    "holdings.org",
    "enterprises.com",
    "industries.net",
    "systems.org",
    "technologies.com",
    "solutions.net",
    "services.org",
    "consulting.com",
]

CITIES = [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Charlotte",
    "San Francisco",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Washington",
    "Boston",
    "El Paso",
    "Nashville",
    "Detroit",
    "Oklahoma City",
    "Portland",
    "Las Vegas",
    "Memphis",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Mesa",
    "Kansas City",
    "Atlanta",
    "Long Beach",
    "Colorado Springs",
    "Raleigh",
    "Miami",
    "Virginia Beach",
    "Omaha",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Arlington",
    "Tampa",
    "New Orleans",
    "Wichita",
    "Cleveland",
    "Bakersfield",
    "Aurora",
    "Anaheim",
    "Honolulu",
    "Santa Ana",
    "Corpus Christi",
    "Riverside",
    "Lexington",
    "Stockton",
    "Henderson",
    "Saint Paul",
    "St. Louis",
    "Milwaukee",
    "Milwaukee",
    "Milwaukee",
    "Milwaukee",
    "Milwaukee",
    "Milwaukee",
    "Milwaukee",
]

STATES = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
]

COUNTRIES = [
    "United States",
    "Canada",
    "Mexico",
    "United Kingdom",
    "Germany",
    "France",
    "Italy",
    "Spain",
    "Netherlands",
    "Sweden",
    "Norway",
    "Denmark",
    "Finland",
    "Switzerland",
    "Austria",
    "Belgium",
    "Ireland",
    "Portugal",
    "Greece",
    "Poland",
    "Czech Republic",
    "Hungary",
    "Slovakia",
    "Slovenia",
    "Croatia",
    "Romania",
    "Bulgaria",
    "Estonia",
    "Latvia",
    "Lithuania",
    "Japan",
    "South Korea",
    "China",
    "India",
    "Australia",
    "New Zealand",
    "Singapore",
    "Hong Kong",
    "Taiwan",
    "Thailand",
    "Malaysia",
    "Indonesia",
    "Philippines",
    "Vietnam",
    "Brazil",
    "Argentina",
    "Chile",
    "Colombia",
    "Peru",
    "Venezuela",
    "Uruguay",
    "Paraguay",
    "Bolivia",
    "Ecuador",
    "Guyana",
    "Suriname",
]

OPPORTUNITY_NAMES = [
    "Enterprise Software License",
    "Cloud Migration Project",
    "Digital Transformation Initiative",
    "CRM Implementation",
    "ERP System Upgrade",
    "Data Analytics Platform",
    "AI/ML Solutions",
    "Cybersecurity Services",
    "IT Infrastructure Modernization",
    "Mobile App Development",
    "Website Redesign",
    "E-commerce Platform",
    "Marketing Automation",
    "Sales Enablement Tools",
    "Customer Support System",
    "HR Management Platform",
    "Financial Management Software",
    "Supply Chain Optimization",
    "Inventory Management System",
    "Business Intelligence Dashboard",
    "API Integration Services",
    "Database Migration",
    "Network Security Audit",
    "Compliance Consulting",
    "Training and Development",
    "Process Optimization",
    "Quality Assurance Services",
    "Project Management Tools",
    "Communication Platform",
    "Collaboration Software",
    "Document Management System",
    "Workflow Automation",
    "Performance Monitoring",
    "Backup and Recovery",
    "Disaster Recovery Plan",
    "Business Continuity",
    "Risk Assessment",
    "Security Audit",
    "Penetration Testing",
    "Vulnerability Assessment",
    "Compliance Review",
    "Regulatory Consulting",
    "Legal Advisory",
    "Financial Planning",
    "Investment Analysis",
    "Market Research",
    "Competitive Analysis",
    "Strategic Planning",
    "Change Management",
    "Organizational Development",
    "Leadership Training",
    "Team Building",
    "Product Development",
    "Market Entry Strategy",
    "International Expansion",
    "Partnership Development",
    "Merger and Acquisition",
    "Due Diligence",
    "Valuation Services",
    "Transaction Support",
    "Post-Merger Integration",
    "Divestiture Support",
    "Restructuring Advisory",
    "Turnaround Services",
    "Interim Management",
    "Executive Search",
    "Talent Acquisition",
    "Succession Planning",
    "Performance Management",
    "Employee Engagement",
    "Culture Transformation",
    "Diversity and Inclusion",
    "Sustainability Consulting",
    "Environmental Compliance",
    "Carbon Footprint Analysis",
    "Green Technology",
    "Renewable Energy",
    "Energy Efficiency",
    "Waste Reduction",
    "Water Management",
    "Air Quality",
    "Noise Control",
    "Environmental Impact Assessment",
    "Sustainability Reporting",
    "ESG Consulting",
]

OPPORTUNITY_DESCRIPTIONS = [
    "Comprehensive solution for enterprise needs",
    "Scalable platform for business growth",
    "Integrated system for improved efficiency",
    "Advanced technology for competitive advantage",
    "Streamlined processes for better productivity",
    "Robust infrastructure for reliability",
    "User-friendly interface for enhanced experience",
    "Secure environment for data protection",
    "Flexible configuration for customization",
    "Cost-effective solution for budget optimization",
    "Future-proof technology for long-term value",
    "Proven methodology for guaranteed results",
    "Expert support for seamless implementation",
    "Comprehensive training for user adoption",
    "Ongoing maintenance for continuous operation",
    "Regular updates for latest features",
    "24/7 support for critical operations",
    "Dedicated team for project success",
    "Best practices for industry standards",
    "Innovative approach for breakthrough results",
    "Collaborative process for stakeholder alignment",
    "Transparent communication for project clarity",
    "Risk mitigation for project security",
    "Quality assurance for deliverable excellence",
    "Timeline management for on-time delivery",
    "Budget control for cost predictability",
    "Change management for smooth transition",
    "Knowledge transfer for sustainability",
    "Documentation for future reference",
    "Lessons learned for continuous improvement",
]


def _permuted(id_: int, min_v: int, max_v: int, step: int, a_hint: int, b: int) -> int:
    min_a = ((min_v + step - 1) // step) * step
    max_a = (max_v // step) * step
    K = (max_a - min_a) // step + 1
    x = id_ % K
    a = a_hint
    while gcd(a, K) != 1:
        a += 1
    return min_a + ((a * x + b) % K) * step


def generate_accounts(count: int = 1000) -> list[dict]:
    rows = []
    for i in range(count):
        company = COMPANY_NAMES[i % len(COMPANY_NAMES)]
        rows.append(
            {
                "name": company,
                "industry": INDUSTRIES[i % len(INDUSTRIES)],
                "website": f"https://www.{company.lower().replace(' ', '').replace('.', '').replace(',', '')}.com",
                "phone": f"+1-555-{1000 + (i % 9000):04d}",
                "address": f"{100 + (i % 9000)} {CITIES[i % len(CITIES)]} Street",
                "city": CITIES[i % len(CITIES)],
                "state": STATES[i % len(STATES)],
                "country": COUNTRIES[i % len(COUNTRIES)],
                "region": REGIONS[i % len(REGIONS)],
                "annual_revenue": _permuted(i, 100_000, 10_000_000, 10_000, 1_234_567, 9_876),
                "employee_count": 10 + (i % 100) * 50,
            }
        )
    return rows


def generate_leads(count: int = 2000) -> list[dict]:
    score_map = {
        "new": 20,
        "contacted": 40,
        "qualified": 60,
        "proposal": 80,
        "negotiation": 90,
        "closed-won": 100,
        "closed-lost": 0,
    }
    rows = []
    for i in range(count):
        first = FIRST_NAMES[i % len(FIRST_NAMES)]
        last = LAST_NAMES[i % len(LAST_NAMES)]
        status = LEAD_STATUSES[i % len(LEAD_STATUSES)]
        domain = EMAIL_DOMAINS[i % len(EMAIL_DOMAINS)]
        source = LEAD_SOURCES[i % len(LEAD_SOURCES)]
        industry = INDUSTRIES[i % len(INDUSTRIES)]
        company = COMPANY_NAMES[i % len(COMPANY_NAMES)]
        job_title = JOB_TITLES[i % len(JOB_TITLES)]
        rows.append(
            {
                "first_name": first,
                "last_name": last,
                "email": f"{first.lower()}.{last.lower()}@{domain}",
                "phone": f"+1-555-{2000 + (i % 8000):04d}",
                "company": company,
                "job_title": job_title,
                "industry": industry,
                "source": source,
                "status": status,
                "score": score_map.get(status, 20),
                "notes": f"Lead from {source} for {industry} industry. Contact at {company} as {job_title}.",
            }
        )
    return rows


def generate_contacts(accounts: list[dict]) -> list[dict]:
    rows = []
    contact_id = 0
    for account in accounts:
        first = FIRST_NAMES[contact_id % len(FIRST_NAMES)]
        last = LAST_NAMES[contact_id % len(LAST_NAMES)]
        domain = EMAIL_DOMAINS[contact_id % len(EMAIL_DOMAINS)]
        slug = account["name"].lower().replace(" ", "").replace(".", "").replace(",", "")
        rows.append(
            {
                "first_name": first,
                "last_name": last,
                "email": f"{first.lower()}.{last.lower()}@{slug}.{domain}",
                "phone": f"+1-555-{3000 + (contact_id % 7000):04d}",
                "job_title": JOB_TITLES[contact_id % len(JOB_TITLES)],
                "department": DEPARTMENTS[contact_id % len(DEPARTMENTS)],
                "is_primary": 1,
                "account_id": account["id"],
            }
        )
        contact_id += 1
    return rows


def generate_opportunities(accounts: list[dict]) -> list[dict]:
    prob_map = {
        "prospecting": 0.1,
        "qualification": 0.3,
        "proposal": 0.6,
        "negotiation": 0.8,
        "closed-won": 1.0,
        "closed-lost": 0.0,
    }
    rows = []
    opp_id = 0
    for idx, account in enumerate(accounts):
        if idx % 5 != 0:
            continue
        for _ in range(2):
            stage = OPPORTUNITY_STAGES[opp_id % len(OPPORTUNITY_STAGES)]
            close_date = (datetime.now() + timedelta(days=30 + (opp_id % 365))).strftime("%Y-%m-%dT%H:%M:%S")
            opp_name = OPPORTUNITY_NAMES[opp_id % len(OPPORTUNITY_NAMES)]
            rows.append(
                {
                    "name": f"{account['name']} - {opp_name}",
                    "description": OPPORTUNITY_DESCRIPTIONS[opp_id % len(OPPORTUNITY_DESCRIPTIONS)],
                    "value": float(_permuted(opp_id, 5_000, 500_000, 1_000, 1_664_525, 12_345)),
                    "currency": "USD",
                    "stage": stage,
                    "probability": prob_map.get(stage, 0.5),
                    "close_date": close_date,
                    "account_id": account["id"],
                }
            )
            opp_id += 1
    return rows


def seed_database(conn: sqlite3.Connection) -> None:
    print("Seeding database with sample data...")

    print("Generating 1000 accounts...")
    account_rows = generate_accounts(1000)
    conn.executemany(
        "INSERT INTO accounts (name,industry,website,phone,address,city,state,country,region,annual_revenue,employee_count) VALUES (?,?,?,?,?,?,?,?,?,?,?)",
        [
            (
                r["name"],
                r["industry"],
                r["website"],
                r["phone"],
                r["address"],
                r["city"],
                r["state"],
                r["country"],
                r["region"],
                r["annual_revenue"],
                r["employee_count"],
            )
            for r in account_rows
        ],
    )
    conn.commit()
    accounts_with_ids = [dict(r) for r in conn.execute("SELECT id, name FROM accounts").fetchall()]

    print("Generating 2000 leads...")
    lead_rows = generate_leads(2000)
    conn.executemany(
        "INSERT INTO leads (first_name,last_name,email,phone,company,job_title,industry,source,status,score,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?)",
        [
            (
                r["first_name"],
                r["last_name"],
                r["email"],
                r["phone"],
                r["company"],
                r["job_title"],
                r["industry"],
                r["source"],
                r["status"],
                r["score"],
                r["notes"],
            )
            for r in lead_rows
        ],
    )
    conn.commit()

    print("Generating contacts...")
    contact_rows = generate_contacts(accounts_with_ids)
    conn.executemany(
        "INSERT INTO contacts (first_name,last_name,email,phone,job_title,department,is_primary,account_id) VALUES (?,?,?,?,?,?,?,?)",
        [
            (
                r["first_name"],
                r["last_name"],
                r["email"],
                r["phone"],
                r["job_title"],
                r["department"],
                r["is_primary"],
                r["account_id"],
            )
            for r in contact_rows
        ],
    )
    conn.commit()

    print("Generating opportunities...")
    opp_rows = generate_opportunities(accounts_with_ids)
    conn.executemany(
        "INSERT INTO opportunities (name,description,value,currency,stage,probability,close_date,account_id) VALUES (?,?,?,?,?,?,?,?)",
        [
            (
                r["name"],
                r["description"],
                r["value"],
                r["currency"],
                r["stage"],
                r["probability"],
                r["close_date"],
                r["account_id"],
            )
            for r in opp_rows
        ],
    )
    conn.commit()

    print(
        f"Database seeded: {len(account_rows)} accounts, {len(lead_rows)} leads, {len(contact_rows)} contacts, {len(opp_rows)} opportunities"
    )
