[agent.task_decomposition.model]
platform = "rits"
model_name = "google/gemma-4-31B-it"
url="https://inference-3scale-apicast-production.apps.rits.fmaas.res.ibm.com/google-gemma-4-31b-it/v1"
apikey_name = "RITS_API_KEY"
temperature = 0.1
top_p = 1.0
max_tokens = 1000

[agent.planner.model]
platform = "rits"
model_name = "google/gemma-4-31B-it"
url="https://inference-3scale-apicast-production.apps.rits.fmaas.res.ibm.com/google-gemma-4-31b-it/v1"
apikey_name = "RITS_API_KEY"
temperature = 0.1
top_p = 1.0
max_tokens = 7000

[agent.shortlister.model]
platform = "rits"
model_name = "google/gemma-4-31B-it"
url="https://inference-3scale-apicast-production.apps.rits.fmaas.res.ibm.com/google-gemma-4-31b-it/v1"
apikey_name = "RITS_API_KEY"
temperature = 0.1
top_p = 1.0
max_tokens = 7000


[agent.chat.model]
platform = "rits"
model_name = "google/gemma-4-31B-it"
url="https://inference-3scale-apicast-production.apps.rits.fmaas.res.ibm.com/google-gemma-4-31b-it/v1"
apikey_name = "RITS_API_KEY"
temperature = 0.1
top_p = 1.0
max_tokens = 5000

[agent.plan_controller.model]
platform = "rits"
model_name = "google/gemma-4-31B-it"
url="https://inference-3scale-apicast-production.apps.rits.fmaas.res.ibm.com/google-gemma-4-31b-it/v1"
apikey_name = "RITS_API_KEY"
temperature = 0.1
top_p = 1.0
max_tokens = 5000


[agent.final_answer.model]
platform = "rits"
model_name = "google/gemma-4-31B-it"
url="https://inference-3scale-apicast-production.apps.rits.fmaas.res.ibm.com/google-gemma-4-31b-it/v1"
apikey_name = "RITS_API_KEY"
temperature = 0.1
top_p = 1.0
max_tokens = 15000

[agent.code.model]
platform = "rits"
model_name = "google/gemma-4-31B-it"
url="https://inference-3scale-apicast-production.apps.rits.fmaas.res.ibm.com/google-gemma-4-31b-it/v1"
apikey_name = "RITS_API_KEY"
temperature = 0.1
top_p = 1.0
max_tokens = 3000

[agent.code_planner.model]
platform = "rits"
model_name = "google/gemma-4-31B-it"
url="https://inference-3scale-apicast-production.apps.rits.fmaas.res.ibm.com/google-gemma-4-31b-it/v1"
apikey_name = "RITS_API_KEY"
temperature = 0.1
top_p = 1.0
max_tokens = 3000

[agent.qa.model]
platform = "rits"
model_name = "google/gemma-4-31B-it"
url="https://inference-3scale-apicast-production.apps.rits.fmaas.res.ibm.com/google-gemma-4-31b-it/v1"
apikey_name = "RITS_API_KEY"
temperature = 0.1
top_p = 1.0
max_tokens = 4000

[agent.action.model]
platform = "rits"
model_name = "google/gemma-4-31B-it"
url="https://inference-3scale-apicast-production.apps.rits.fmaas.res.ibm.com/google-gemma-4-31b-it/v1"
apikey_name = "RITS_API_KEY"
temperature = 0.1
top_p = 1.0
max_tokens = 400

[memory.mem0.model]
platform = "rits"
model_name = "google/gemma-4-31B-it"
url="https://inference-3scale-apicast-production.apps.rits.fmaas.res.ibm.com/google-gemma-4-31b-it/v1"
apikey_name = "RITS_API_KEY"
temperature = 0.1
top_p = 1.0
max_tokens = 1000

[memory.milvus.step_processing.model]
platform = "rits"
model_name = "google/gemma-4-31B-it"
url="https://inference-3scale-apicast-production.apps.rits.fmaas.res.ibm.com/google-gemma-4-31b-it/v1"
apikey_name = "RITS_API_KEY"
temperature = 0.1
top_p = 1.0
max_tokens = 1000

[memory.milvus.fact_extraction.model]
platform = "rits"
model_name = "google/gemma-4-31B-it"
url="https://inference-3scale-apicast-production.apps.rits.fmaas.res.ibm.com/google-gemma-4-31b-it/v1"
apikey_name = "RITS_API_KEY"
temperature = 0.1
top_p = 1.0
max_tokens = 1000

[memory.tips_extractor.model]
platform = "rits"
model_name = "google/gemma-4-31B-it"
url="https://inference-3scale-apicast-production.apps.rits.fmaas.res.ibm.com/google-gemma-4-31b-it/v1"
apikey_name = "RITS_API_KEY"
temperature = 0.1
top_p = 1.0
max_tokens = 5000